version: '3.5'
services:
  rulemanager:
    container_name: 'rulemanager'
    build:
      context: ./
      dockerfile: ./docker/dev/Dockerfile
      args:
        ADFS_USER: ${ADFS_USER}
    volumes:
      - ./:/home/rulemanager
      - ./docker/dev/data/sds:/data/temp_archive
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_SESSION_TOKEN=$AWS_SESSION_TOKEN}

  wfcatalog_mongo:
    image: 'mongo'
    hostname: 'wfcatalog_mongo'
    container_name: 'wfcatalog_mongo'
    volumes:
      - wfcat_mongodb:/data/db

  ppsd_webservice:
    container_name: 'ppsd_webservice'
    build:
      context: ${PPSD_WS_DIR}
      dockerfile: ${PPSD_WS_DIR}/Dockerfile
    depends_on:
      - ppsd_mongo
    ports:
      - '3000:3000'
    volumes:
      - ${PPSD_WS_DIR}/config.json:/usr/src/app/config.json
      - /dev/null:/tmp/ppsd-service/logs/PPSD-Webservice-Trace.log

  ppsd_mongo:
    image: 'mongo'
    hostname: 'ppsd_mongo'
    container_name: 'ppsd_mongo'
    volumes:
      - ppsd_mongodb:/data/db


  wfcatalog_service:
    container_name: 'wfcatalog_service'
    hostname: 'wfcatalog_service'
    build:
      context: ${WFCAT_WS_DIR}/service
      dockerfile: ${WFCAT_WS_DIR}/service/Dockerfile
    depends_on:
      - wfcatalog_mongo
    ports:
      - 8888:8888

volumes:
  wfcat_mongodb:
  ppsd_mongodb:
