# TODO: configuration as docker configs, secrets or env?
# TODO: aws credentials as secrets or in config file?
# TODO: volume temp archive (not read-only)
# TODO: dependency on ppsd-webservice network?

version: '3.5'
services:
  rulemanager:
    container_name: 'rulemanager'
    build:
      context: ./
      dockerfile: ./docker/acpt-prd/Dockerfile
    user: sysop:sysop
    volumes:
      - /data/shared/sds:/data/temp_archive:ro
      - /data/shared/quarantinesds:/data/quarantine:ro
      - /data/seismo/rulemanager:/var/rulemanager
      - /home/sysop/log:/tmp/rulemanager/logs
    networks:
      - wfcatalog_net
      - ppsd_net
    secrets:
      - source: rulemanager_config
        target: /home/rulemanager/configuration.py
      - source: aws_config
        target: /home/sysop/.aws

secrets:
  rulemanager_config:
    file: ./configuration.py
  aws_config:
    file: ${HOME}/.aws
networks:
  wfcatalog_net:
    external: true
  ppsd_net:
    external: true
