# rulemanager -> volumes and cfg?
# rulemanager -> aws credentials as docker secrets
# wfcatalog -> cfg?
# ppsd-webservice -> dockerfile todo
# mongodb -> docker run -p 27017:27017 --name mongo_server -v $(pwd)/mongodb:/data/db -d mongo:4.0.5-xenial

version: '3.5'
services:
  rulemanager:
    container_name: 'rulemanager'
    build:
      context: ./
      dockerfile: ./dev-env/Dockerfile
    volumes:
      - ./:/home/rulemanager
      - ./dev-env/data/sds:/data/temp_archive
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}

  wfcatalog_mongo:
    image: 'mongo'
    hostname: 'wfcatalog_mongo'
    container_name: 'wfcatalog_mongo'
    volumes:
      - wfcat_mongodb:/data/db

  ppsd_webservice:
    image: 'ppsd_webservice'
    container_name: 'ppsd_webservice'
    depends_on:
      - ppsd_mongo
    ports:
      - '3000:3000'

  ppsd_mongo:
    image: 'mongo'
    hostname: 'ppsd_mongo'
    container_name: 'ppsd_mongo'
    volumes:
      - ppsd_mongodb:/data/db


  wfcatalog_service:
    image: 'rm/node-ws-wfcat:1'
    hostname: 'wfcatalog_service'
    container_name: 'wfcatalog_service'
    depends_on:
      - wfcatalog_mongo
    ports:
      - 8888:8888

volumes:
  wfcat_mongodb:
  ppsd_mongodb:
